//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorForms.Pages
{
	public partial class HelloModel
	{
		protected FineUICore.Button btnHello;
	}
}
