//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorForms.Pages
{
	public partial class IndexModel
	{
		protected FineUICore.Panel mainPanel;
		protected FineUICore.Panel sidebarRegion;
		protected FineUICore.Panel sideheaderTopPanel;
		protected FineUICore.Panel leftPanel;
		protected FineUICore.Tree treeMenu;
		protected FineUICore.Panel bodyRegion;
		protected FineUICore.Panel topPanel;
		protected FineUICore.Button btnThemeSelect;
		protected FineUICore.TabStrip mainTabStrip;
		protected FineUICore.Tab tabHomepage;
		protected FineUICore.Window windowThemeRoller;
	}
}
