//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.QuickStart
{
	public partial class MovieEditModel
	{
		protected FineUICore.Panel Panel1;
		protected FineUICore.Button BtnClose;
		protected FineUICore.Button btnSaveClose;
		protected FineUICore.SimpleForm SimpleForm1;
	}
}
