//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorPages
{
	public partial class MovieModel
	{
		protected FineUICore.Grid Grid1;
		protected FineUICore.Panel Panel1;
		protected FineUICore.TwinTriggerBox ttbSearchMessage;
		protected FineUICore.Toolbar Toolbar1;
		protected FineUICore.Button btnNew;
		protected FineUICore.Window Window1;
	}
}
